"""initial schema

Revision ID: 2d6bee1ebe86
Revises: 
Create Date: 2026-08-19 12:52:02.682688
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '2d6bee1ebe86'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None



LATEST_VINTAGE_VIEW = """
CREATE VIEW latest_observations AS
SELECT DISTINCT ON (series_id, period_start)
       id, series_id, period_start, period_end, value, quantity, quantity_unit,
       unit_value, vintage_date, release_date, retrieved_at
FROM observations
ORDER BY series_id, period_start, vintage_date DESC
"""

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_prices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close_usd', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_prices')),
    sa.UniqueConstraint('symbol', 'date', name='uq_benchmark_symbol_date')
    )
    op.create_table('fx_rates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rate_to_usd', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fx_rates')),
    sa.UniqueConstraint('currency', 'date', name='uq_fx_currency_date')
    )
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('bucket', sa.Enum('actuation', 'precision_mfg', 'materials', 'sensing', 'compute_power', 'energy', 'assembly', name='bucket'), nullable=False),
    sa.Column('break_point_tier', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('evidence_grade', sa.Enum('measured', 'disclosed', 'inferred', 'estimated', name='evidence_grade'), nullable=True),
    sa.Column('methodology_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nodes')),
    sa.UniqueConstraint('name', name=op.f('uq_nodes_name'))
    )
    op.create_table('raw_payloads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('params_hash', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_payloads'))
    )
    op.create_index(op.f('ix_raw_payloads_params_hash'), 'raw_payloads', ['params_hash'], unique=False)
    op.create_index(op.f('ix_raw_payloads_source'), 'raw_payloads', ['source'], unique=False)
    op.create_index('ix_raw_payloads_source_fetched', 'raw_payloads', ['source', 'fetched_at'], unique=False)
    op.create_table('securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_ticker', sa.String(length=40), nullable=False),
    sa.Column('exchange_mic', sa.String(length=10), nullable=True),
    sa.Column('local_code', sa.String(length=30), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('data_source', sa.String(length=60), nullable=True),
    sa.Column('source_symbol', sa.String(length=60), nullable=True),
    sa.Column('coverage_status', sa.Enum('ok', 'partial', 'unavailable', name='coverage_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_securities')),
    sa.UniqueConstraint('display_ticker', name=op.f('uq_securities_display_ticker'))
    )
    op.create_table('baskets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('bucket', sa.Enum('actuation', 'precision_mfg', 'materials', 'sensing', 'compute_power', 'energy', 'assembly', name='bucket'), nullable=True),
    sa.Column('constraint_label', sa.String(length=200), nullable=False),
    sa.Column('purity_grade', sa.Enum('pure', 'mixed', 'narrative', name='purity_grade'), nullable=False),
    sa.Column('is_demand_side', sa.Boolean(), nullable=False),
    sa.Column('is_shared_node', sa.Boolean(), nullable=False),
    sa.Column('thesis_note', sa.Text(), nullable=True),
    sa.Column('caveat_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name=op.f('fk_baskets_node_id_nodes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_baskets')),
    sa.UniqueConstraint('name', name=op.f('uq_baskets_name'))
    )
    op.create_index(op.f('ix_baskets_node_id'), 'baskets', ['node_id'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close_local', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('close_usd', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('fx_rate', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_prices_security_id_securities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prices')),
    sa.UniqueConstraint('security_id', 'date', name='uq_prices_security_date')
    )
    op.create_index('ix_prices_date', 'prices', ['date'], unique=False)
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('cadence', sa.Enum('daily', 'weekly', 'monthly', 'quarterly', 'annual', name='cadence'), nullable=False),
    sa.Column('unit', sa.String(length=60), nullable=True),
    sa.Column('evidence_grade', sa.Enum('measured', 'disclosed', 'inferred', 'estimated', name='evidence_grade'), nullable=False),
    sa.Column('geography', sa.String(length=60), nullable=False),
    sa.Column('partner_geography', sa.String(length=60), nullable=True),
    sa.Column('tariff_code', sa.String(length=40), nullable=True),
    sa.Column('tariff_nomenclature', sa.String(length=40), nullable=True),
    sa.Column('flow_direction', sa.Enum('import', 'export', 'production', 'orders', name='flow_direction'), nullable=False),
    sa.Column('methodology_note', sa.Text(), nullable=True),
    sa.Column('known_limitations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name=op.f('fk_series_node_id_nodes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series')),
    sa.UniqueConstraint('source', 'name', 'geography', 'partner_geography', name='uq_series_ident')
    )
    op.create_index(op.f('ix_series_node_id'), 'series', ['node_id'], unique=False)
    op.create_table('basket_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.Date(), nullable=False),
    sa.Column('removed_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], name=op.f('fk_basket_members_basket_id_baskets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_basket_members_security_id_securities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_basket_members')),
    sa.UniqueConstraint('basket_id', 'security_id', 'added_at', name='uq_basket_member_spell')
    )
    op.create_index(op.f('ix_basket_members_basket_id'), 'basket_members', ['basket_id'], unique=False)
    op.create_index(op.f('ix_basket_members_security_id'), 'basket_members', ['security_id'], unique=False)
    op.create_table('basket_returns',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('window', sa.Enum('1d', '7d', '30d', 'ytd', name='return_window'), nullable=False),
    sa.Column('return_raw', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('return_vs_benchmark', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('breadth', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('constituents_priced', sa.Integer(), nullable=False),
    sa.Column('constituents_total', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], name=op.f('fk_basket_returns_basket_id_baskets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_basket_returns')),
    sa.UniqueConstraint('basket_id', 'date', 'window', name='uq_basket_returns_key')
    )
    op.create_index('ix_basket_returns_basket_date', 'basket_returns', ['basket_id', 'date'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('quantity_unit', sa.String(length=40), nullable=True),
    sa.Column('unit_value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('vintage_date', sa.Date(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_observations_series_id_series'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observations')),
    sa.UniqueConstraint('series_id', 'period_start', 'vintage_date', name='uq_observations_vintage')
    )
    op.create_index('ix_observations_series_period', 'observations', ['series_id', 'period_start'], unique=False)
    op.create_table('tripwires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('observable_series_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.Enum('above', 'below', name='tripwire_direction'), nullable=True),
    sa.Column('threshold', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('open', 'confirmed', 'falsified', name='tripwire_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name=op.f('fk_tripwires_node_id_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observable_series_id'], ['series.id'], name=op.f('fk_tripwires_observable_series_id_series'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tripwires'))
    )
    op.create_index(op.f('ix_tripwires_node_id'), 'tripwires', ['node_id'], unique=False)
    # ### end Alembic commands ###

    # Latest-vintage read surface. Observations are append-only by vintage,
    # so 'the number as it stands today' is a pick, never an overwrite.
    op.execute(LATEST_VINTAGE_VIEW)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS latest_observations")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tripwires_node_id'), table_name='tripwires')
    op.drop_table('tripwires')
    op.drop_index('ix_observations_series_period', table_name='observations')
    op.drop_table('observations')
    op.drop_index('ix_basket_returns_basket_date', table_name='basket_returns')
    op.drop_table('basket_returns')
    op.drop_index(op.f('ix_basket_members_security_id'), table_name='basket_members')
    op.drop_index(op.f('ix_basket_members_basket_id'), table_name='basket_members')
    op.drop_table('basket_members')
    op.drop_index(op.f('ix_series_node_id'), table_name='series')
    op.drop_table('series')
    op.drop_index('ix_prices_date', table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_baskets_node_id'), table_name='baskets')
    op.drop_table('baskets')
    op.drop_table('securities')
    op.drop_index('ix_raw_payloads_source_fetched', table_name='raw_payloads')
    op.drop_index(op.f('ix_raw_payloads_source'), table_name='raw_payloads')
    op.drop_index(op.f('ix_raw_payloads_params_hash'), table_name='raw_payloads')
    op.drop_table('raw_payloads')
    op.drop_table('nodes')
    op.drop_table('fx_rates')
    op.drop_table('benchmark_prices')
    # ### end Alembic commands ###
